touchscreen/xiaomi: Fix error cause a function declaration is deprecated
clang-15 warns:

../drivers/input/touchscreen/xiaomi/xiaomi_touch.c:137:37: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct class *get_xiaomi_touch_class()
                                    ^
                                     void
../drivers/input/touchscreen/xiaomi/xiaomi_touch.c:142:36: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct device *get_xiaomi_touch_dev()
                                   ^
                                    void
2 errors generated.

Signed-off-by: hachiman270 <hachiman270@gmail.com>