fs: sdFat: Allow using iversion.h on 4.14 kernel
We already have iversion.h now. Use it to fix compilation like following:

../fs/sdfat/core.c:52:9: error: returning 'atomic64_t' from a function with incompatible result type 'u64' (aka 'unsigned long long')
        return inode->i_version;
               ^~~~~~~~~~~~~~~~
../fs/sdfat/sdfat.c:146:19: error: assigning to 'atomic64_t' from incompatible type 'u64' (aka 'unsigned long long')
        inode->i_version = val;
                         ^ ~~~
../fs/sdfat/sdfat.c:150:9: error: returning 'atomic64_t' from a function with incompatible result type 'u64' (aka 'unsigned long long')
        return inode->i_version;
               ^~~~~~~~~~~~~~~~
../fs/sdfat/sdfat.c:2422:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(dir);
        ^
../fs/sdfat/sdfat.c:2422:2: note: did you mean 'inode_set_iversion'?
../fs/sdfat/sdfat.c:144:20: note: 'inode_set_iversion' declared here
static inline void inode_set_iversion(struct inode *inode, u64 val)
                   ^
../fs/sdfat/sdfat.c:2585:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(dir);
        ^
../fs/sdfat/sdfat.c:2637:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(dir);
        ^
../fs/sdfat/sdfat.c:2691:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(dir);
        ^
../fs/sdfat/sdfat.c:2742:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(dir);
        ^
../fs/sdfat/sdfat.c:2790:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(new_dir);
        ^
../fs/sdfat/sdfat.c:3949:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(inode);
        ^
../fs/sdfat/sdfat.c:4934:2: error: implicit declaration of function 'inode_inc_iversion' [-Werror,-Wimplicit-function-declaration]
        inode_inc_iversion(inode);
        ^
10 errors generated.

Signed-off-by: atndko <z1281552865@gmail.com>
Signed-off-by: hachiman270 <hachiman270@gmail.com>
(cherry picked from commit 197c3e01b948203629987d12c4b6fd1bd8ac7d23)